cask "font-berkeley-mono" do
  version "2.002"
  sha256 "dc052c08613e4308b237f8b7c8769ff594802f39f9f178ee67a27d968c4f3e96"

  url "https://brew.czyt.eu.org/fonts/berkeley-mono/TX-02-#{version}.zip"
  name "Berkeley Mono"
  desc "Monospaced font for coding"
  homepage "https://berkeleygraphics.com/typefaces/berkeley-mono/"

  font "TX-02-Bold-Condensed-Oblique.otf"
  font "TX-02-Bold-Condensed.otf"
  font "TX-02-Bold-Oblique.otf"
  font "TX-02-Bold-SemiCondensed-Oblique.otf"
  font "TX-02-Bold-SemiCondensed.otf"
  font "TX-02-Bold.otf"
  font "TX-02-Condensed-Oblique.otf"
  font "TX-02-Condensed.otf"
  font "TX-02-ExtraBold-Condensed-Oblique.otf"
  font "TX-02-ExtraBold-Condensed.otf"
  font "TX-02-ExtraBold-Oblique.otf"
  font "TX-02-ExtraBold-SemiCondensed-Oblique.otf"
  font "TX-02-ExtraBold-SemiCondensed.otf"
  font "TX-02-ExtraBold.otf"
  font "TX-02-Medium-Condensed-Oblique.otf"
  font "TX-02-Medium-Condensed.otf"
  font "TX-02-Medium-Oblique.otf"
  font "TX-02-Medium-SemiCondensed-Oblique.otf"
  font "TX-02-Medium-SemiCondensed.otf"
  font "TX-02-Medium.otf"
  font "TX-02-Oblique.otf"
  font "TX-02-Regular.otf"
  font "TX-02-Retina-Condensed-Oblique.otf"
  font "TX-02-Retina-Condensed.otf"
  font "TX-02-Retina-Oblique.otf"
  font "TX-02-Retina-SemiCondensed-Oblique.otf"
  font "TX-02-Retina-SemiCondensed.otf"
  font "TX-02-Retina.otf"
  font "TX-02-SemiCondensed-Oblique.otf"
  font "TX-02-SemiCondensed.otf"
end
