cask "font-monolisa" do
  version "2.016"
  sha256 "7a4aecb23f9767fcca43393af74009e43f3c869ed9839eae2d0178a6dea260a7"

  url "https://brew.czyt.eu.org/fonts/monolisa/#{version}.zip"
  name "MonoLisa"
  desc "Monospaced font designed for developers"
  homepage "https://www.monolisa.dev/"

  font "MonoLisa/MonoLisa-Black.ttf"
  font "MonoLisa/MonoLisa-BlackItalic.ttf"
  font "MonoLisa/MonoLisa-Bold.ttf"
  font "MonoLisa/MonoLisa-BoldItalic.ttf"
  font "MonoLisa/MonoLisa-ExtraBold.ttf"
  font "MonoLisa/MonoLisa-ExtraBoldItalic.ttf"
  font "MonoLisa/MonoLisa-ExtraLight.ttf"
  font "MonoLisa/MonoLisa-ExtraLightItalic.ttf"
  font "MonoLisa/MonoLisa-Light.ttf"
  font "MonoLisa/MonoLisa-LightItalic.ttf"
  font "MonoLisa/MonoLisa-Medium.ttf"
  font "MonoLisa/MonoLisa-MediumItalic.ttf"
  font "MonoLisa/MonoLisa-Regular.ttf"
  font "MonoLisa/MonoLisa-RegularItalic.ttf"
  font "MonoLisa/MonoLisa-SemiBold.ttf"
  font "MonoLisa/MonoLisa-SemiBoldItalic.ttf"
  font "MonoLisa/MonoLisa-Thin.ttf"
  font "MonoLisa/MonoLisa-ThinItalic.ttf"
  font "MonoLisa Variable/MonoLisaVariableItalic.ttf"
  font "MonoLisa Variable/MonoLisaVariableNormal.ttf"
end
